# Generated by Django 4.0.3 on 2022-12-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslistitem',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='buslistitem',
            name='last_name',
            field=models.TextField(null=True),
        ),
    ]
