# Generated by Django 4.0.3 on 2022-12-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0002_buslistitem_date_buslistitem_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='buslistitem',
            name='city',
            field=models.TextField(null=True),
        ),
    ]
